### ISSUE TITLE
Ubuntu 14.04.1 installation issues: missing files, syntax errors

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/RetroRig#165]
Reported by: @Lockzi

Issue:

On my clean Ubuntu 14.04.1 install I ran RetroRig
<Lockzi> It is stuck on '/home/administrator/RetroRig/XBMC-cfgs/extra/RetroRig.desktop' -> '/home/administrator/.config/autostart/RetroRig.desktop'
<Lockzi> I also see multiple: sed: can't read /home/administrator/.retrorig/.dolphin-emu/Wii/Config/WiimoteNew.ini: No such file or directory

**Comment by Lockzi** [comment]
Seems to not be giving this error any more.

Thanks PK64 ;)

**Comment by ProfessorKaos64** [comment]
Cool. Yea I will figure out a better logging system. It's hard with scripts. I'll figure something out. Thanks @Lockzi
