### ISSUE TITLE
Nintendo 64 games are not imported by RCB

### ISSUE THREAD

**Issue by Lockzi** [ProfessorKaos64/RetroRig#170]
17:38:13 T:140482190894848  NOTICE: RCB_INFO: current Rom Collection: Nintendo 64
17:38:13 T:140482190894848  NOTICE: RCB_INFO: ignoreOnScan: False
17:38:13 T:140482190894848  NOTICE: RCB_INFO: update is allowed for current rom collection: True
17:38:13 T:140482190894848  NOTICE: RCB_INFO: max folder depth: 99
17:38:13 T:140482190894848  NOTICE: RCB_INFO: Rom path: ['/home/administrator/RetroRig/ROMs/Nintendo 64/*.v64', '/home/administ$
17:38:13 T:140482190894848  NOTICE: RCB_INFO: Reading rom files
17:38:13 T:140482190894848  NOTICE: RCB_INFO: walkDownPath romPath: /home/administrator/RetroRig/ROMs/Nintendo 64/*.v64
17:38:13 T:140482190894848  NOTICE: RCB_INFO: Running walkdown on: /home/administrator/RetroRig/ROMs/Nintendo 64/*.v64
17:38:13 T:140482190894848  NOTICE: RCB_INFO: Begin getFilesByWildcard. pathName = /home/administrator/RetroRig/ROMs/Nintendo 6$
17:38:13 T:140482190894848  NOTICE: RCB_INFO: dirname: /home/administrator/RetroRig/ROMs/Nintendo 64
17:38:13 T:140482190894848  NOTICE: RCB_INFO: filemask: *.v64
17:38:13 T:140482190894848   ERROR: GetDirectory - Error getting /home/administrator/RetroRig/ROMs/Nintendo 64

The reason is that there is no Nintendo 64 folder in ~/RetroRig/ROMs but rather a mupen64plus folder.

Temporarily fixed it by symbolic linking:
administrator@retroRig:~/RetroRig/ROMs$ ln -s mupen64plus/ Nintendo\ 64

**Comment by beaumanvienna** [comment]
I can confirm this, folder "Nintendo 64" used to be there, but it's not after a fresh install of 0.9.8.2.

**Comment by ProfessorKaos64** [comment]
Sorry about that! Fixed in commit 9be348b
