### ISSUE TITLE
Dolphin Segmentation Fault

### ISSUE THREAD

**Issue by ProfessorKaos64** [ProfessorKaos64/RetroRig#172]
@beaumanvienna Can you confirm? I cannot launch games from the desktop as well. Program launches, but Mario Kart Double Dash gives a segfault. I do get worried that as we progress, it gets harder to try and maintain current packages or emulators like Dolphin that get updated a lot. I can also confirm that the same behavior occurs when using ppa:glennric/dolphin-emu .

**Comment by ProfessorKaos64** [comment]
My bad, didn't load the proprietary drivers ...

**Comment by beaumanvienna** [comment]
OK, noticed. Don't worry too much about our PPA versions of the emulators, they still should be more recent than the versions that are provided under Ubuntu. We should re-base them every once in while, depending on how much changes the actual program sees. When it comes to less finished emulators like dolphin-emu, we need to do this a bit more frequent.
