### ISSUE TITLE
Do I really have to click "OK" every few ROMs?

### ISSUE THREAD

**Issue by mesheree** [ProfessorKaos64/RetroRig#176]
So... there are a _LOT_ of ROMs where it can't find metadata, and that's fine, but having to click OK every time it happens (hundreds of times) is pretty annoying...

Two requests:
- Can you just let it do its scraping thing all by itself, and tell me at the end of the process and/or put it in a log file?
- Can you make it a little more difficult to accidentally stop the entire process? (In this case, by accidentally clicking again after clicking the OK button that shouldn't be there in the first place...)

**Comment by mdeguzis** [comment]
I think that is more of  Rom Collection Browser issue than any. I unfortunately am a bit busy with various projects and a new job that is going to require some time to develop skills.
